version: '3.5'
services:
#Services
 rdi:
  build:
    context: build
    args:
     ENVPATH: rdi.env
  hostname: rdi
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   perimetral_dmz:
    ipv4_address: 192.168.120.202
   perimetral_sat:
    ipv4_address: 192.168.112.202
  volumes:
   - iptrdi:/etc/iptables
   - suricata:/etc/suricata
 rde:
  build:
    context: build
    args:
     ENVPATH: rde.env
  hostname: rde
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   perimetral_dmz:
    ipv4_address: 192.168.120.203
   perimetral_ext:
    ipv4_address: 192.168.200.203
  volumes:
   - iptrde:/etc/iptables
   - snort:/etc/snort
   - /lib/modules:/lib/modules
networks:
  perimetral_sat:
    external: true
  perimetral_dmz:
    external: true
  perimetral_ext:
    external: true
volumes:
 iptrdi:
 iptrde:
 snort:
 suricata:
