version: '3.5'
services:
#Services
 rde:
  build:
    context: build
    args:
     ENVPATH: rde.env
  hostname: rde
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   dmz:
    ipv4_address: 192.168.120.203
   ext:
    ipv4_address: 192.168.200.203
  volumes:
   - iptrde:/etc/iptables
   - snort:/etc/snort
networks:
  dmz:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_dmz
    ipam:
     config:
       - subnet: 192.168.120.0/24
  ext:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_ext
    ipam:
     config:
       - subnet: 192.168.200.0/24
volumes:
 iptrde:
 snort:
