version: '3.5'
services:
 debian:
  build:
    context: build
    args:
     ENVPATH: debian.env
  command: exit
  networks:
   wan:
 left:
  image: redes_ipsec_debian
  hostname: left
  sysctls:
    net.ipv4.ip_forward: 1
  environment:
   - DISPLAY=${DISPLAY}
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /lib/modules:/lib/modules
  privileged: true
  networks:
   net:
    ipv4_address: 192.168.22.11
 right:
  image: redes_ipsec_debian
  hostname: right
  sysctls:
    net.ipv4.ip_forward: 1
  environment:
   - DISPLAY=${DISPLAY}
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /lib/modules:/lib/modules
  privileged: true
  networks:
   net:
    ipv4_address: 192.168.22.12
 pedro:
  image: redes_ipsec_debian
  hostname: pedro
  environment:
   - DISPLAY=${DISPLAY}
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /lib/modules:/lib/modules
  ports:
   - "3389:3389"
  privileged: true
  networks:
   psoe:
    ipv4_address: 192.168.23.10
 pablo:
  image: redes_ipsec_debian
  hostname: pablo
  environment:
   - DISPLAY=${DISPLAY}
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /lib/modules:/lib/modules
  privileged: true
  networks:
   pp:
    ipv4_address: 192.168.24.10
networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.22.0/24
  psoe:
    driver: ipvlan
    internal: true
    ipam:
     config:
       - subnet: 192.168.23.0/24
  pp:
    driver: ipvlan
    internal: true
    ipam:
     config:
       - subnet: 192.168.24.0/24
  wan:
    driver: ipvlan
    internal: true
    ipam:
     config:
       - subnet: 192.168.25.0/24
