services:
#Services
 wordpress:
  build:
    context: build
    args:
     ENVPATH: wordpress.env
  hostname: wordpress
  privileged: true
  networks:
   perimetral_dmz:
    ipv4_address: 192.168.120.122
  volumes:
   - iptwordpress:/etc/iptables
   - wpmysql:/var/lib/mysql
 moodle:
  build:
    context: build
    args:
     ENVPATH: moodle.env
  hostname: moodle
  privileged: true
  networks:
   perimetral_dmz:
    ipv4_address: 192.168.120.123
  volumes:
   - iptmoodle:/etc/iptables
   - moodmysql:/var/lib/mysql
 dvwa:
  build:
    context: build
    args:
     ENVPATH: dvwa.env
  hostname: dvwa
  privileged: true
  networks:
   perimetral_dmz:
    ipv4_address: 192.168.120.124
  volumes:
   - iptdvwa:/etc/iptables
   - dvwamysql:/var/lib/mysql
networks:
  perimetral_dmz:
    external: true
volumes:
 iptwordpress:
 iptmoodle:
 iptdvwa:
 wpmysql:
 moodmysql:
 dvwamysql:
