version: '3.5'
services:
#Services
 squid:
  build:
    context: build
    args:
     ENVPATH: squid.env
  hostname: squid
  privileged: true
  networks:
   sat:
    ipv4_address: 192.168.112.200
  volumes:
   - iptsquid:/etc/iptables
   - squid:/etc/squid
 nginx:
  build:
    context: build
    args:
     ENVPATH: nginx.env
  hostname: nginx
  privileged: true
  networks:
   ext:
    ipv4_address: 192.168.200.202
  volumes:
   - iptnginx:/etc/iptables
   - nginx:/etc/nginx
networks:
  sat:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_sat
    ipam:
     config:
       - subnet: 192.168.112.0/24
  ext:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_ext
    ipam:
     config:
       - subnet: 192.168.200.0/24
volumes:
 iptsquid:
 iptnginx:
 squid:
 nginx:
