version: '3.5'
services:
#Services
 squid:
  build:
    context: build
    args:
     ENVPATH: squid.env
  hostname: squid
  cap_add:
  - ALL
  networks:
   perimetral_sat:
    ipv4_address: 192.168.112.200
  volumes:
   - iptsquid:/etc/iptables
   - squid:/etc/squid
networks:
  perimetral_sat:
    external: true
volumes:
 iptsquid:
 squid:
