version: '3.5'
services:
#Services
 adm1:
  build:
    context: build
    args:
     ENVPATH: adm.env
  hostname: adm1
  privileged: true
  networks:
   adm:
    ipv4_address: 192.168.110.111
  volumes:
   - iptadm1:/etc/iptables
 adm2:
  build:
    context: build
    args:
     ENVPATH: adm.env
  hostname: adm2
  privileged: true
  networks:
   adm:
    ipv4_address: 192.168.110.112
  volumes:
   - iptadm2:/etc/iptables
 dir1:
  build:
    context: build
    args:
     ENVPATH: dir.env
  hostname: dir1
  privileged: true
  networks:
   dir:
    ipv4_address: 192.168.111.112
  volumes:
   - iptdir1:/etc/iptables
 sat1:
  build:
    context: build
    args:
     ENVPATH: sat.env
  hostname: sat1
  privileged: true
  networks:
   sat:
    ipv4_address: 192.168.112.113
  volumes:
   - iptsat1:/etc/iptables
 sat2:
  build:
    context: build
    args:
     ENVPATH: sat.env
  hostname: sat2
  privileged: true
  networks:
   sat:
    ipv4_address: 192.168.112.122
  volumes:
   - iptsat2:/etc/iptables
 www:
  build:
    context: build
    args:
     ENVPATH: dmz.env
  hostname: www
  privileged: true
  networks:
   dmz:
    ipv4_address: 192.168.120.121
  volumes:
   - iptwww:/etc/iptables
 rl:
  build:
    context: build
    args:
     ENVPATH: rl.env
  hostname: rl
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   adm:
    ipv4_address: 192.168.110.201
   dir:
    ipv4_address: 192.168.111.201
   sat:
    ipv4_address: 192.168.112.201
  volumes:
   - iptrl:/etc/iptables
 rdi:
  build:
    context: build
    args:
     ENVPATH: rdi.env
  hostname: rdi
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   sat:
    ipv4_address: 192.168.112.202
   dmz:
    ipv4_address: 192.168.120.202
  volumes:
   - iptrdi:/etc/iptables
 rde:
  build:
    context: build
    args:
     ENVPATH: rde.env
  hostname: rde
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   dmz:
    ipv4_address: 192.168.120.203
   ext:
    ipv4_address: 192.168.200.203
  volumes:
   - iptrde:/etc/iptables
networks:
  adm:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_adm
    ipam:
     config:
       - subnet: 192.168.110.0/24
  dir:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_dir
    ipam:
     config:
       - subnet: 192.168.111.0/24
  sat:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_sat
    ipam:
     config:
       - subnet: 192.168.112.0/24
  dmz:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_dmz
    ipam:
     config:
       - subnet: 192.168.120.0/24
  ext:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: firewall_ext
    ipam:
     config:
       - subnet: 192.168.200.0/24
volumes:
 iptadm1:
 iptadm2:
 iptdir1:
 iptsat1:
 iptsat2:
 iptwww:
 iptrl:
 iptrdi:
 iptrde:
