version: '3.5'
services:
#Services
 host1x_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1x_2
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridge10:
    ipv4_address: 172.0.10.2
 host1x_3:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1x_3
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridge10:
    ipv4_address: 172.0.10.3
 host1x_4:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1x_4
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridge10:
    ipv4_address: 172.0.10.4
 host1x_5:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1x_5
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridge10:
    ipv4_address: 172.0.10.5
 host0_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host0_2
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  volumes:
   - /lib/modules:/lib/modules
  networks:
   vlbridge0:
    ipv4_address: 172.0.0.2
 host1_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1_2
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   vlan1:
    ipv4_address: 172.0.1.2
 host1_3:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host1_3
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   vlan1:
    ipv4_address: 172.0.1.3
 host2_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host2_2
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   vlan2:
    ipv4_address: 172.0.2.2
 host2_3:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: host2_3
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   vlan2:
    ipv4_address: 172.0.2.3
 hostpf21_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: hostpf21_2
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridgepf20:
    ipv4_address: 172.0.20.2
 hostpf21_3:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: hostpf21_3
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridgepf20:
    ipv4_address: 172.0.20.3
 hostpf22_2:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: hostpf22_2
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridgepf20:
    ipv4_address: 172.0.20.4
 hostpf22_3:
  build:
    context: build
    args:
     ENVPATH: host.env
  hostname: hostpf22_3
  privileged: true
  volumes:
   - /lib/modules:/lib/modules
  networks:
   bridgepf20:
    ipv4_address: 172.0.20.5
networks:
  bridge10:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: bridge10
    ipam:
     config:
       - subnet: 172.0.10.0/24
  vlbridge0:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: vlbridge0
    ipam:
     config:
       - subnet: 172.0.0.0/24
  bridgepf20:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: bridgepf20
    ipam:
     config:
       - subnet: 172.0.20.0/24
  vlan1:
    driver: macvlan
    driver_opts:
     parent: vlbridge0.1
    ipam:
     config:
       - subnet: 172.0.1.0/24
  vlan2:
    driver: macvlan
    driver_opts:
     parent: vlbridge0.2
    ipam:
     config:
       - subnet: 172.0.2.0/24

