version: '3'
services:
#Services
 adm1:
  build: ./adm
  hostname: adm1
  env_file: 
  - "adm/envfile"
  privileged: true
  networks:
   administracion:
    ipv4_address: 192.168.110.111
 adm2:
  build: ./adm
  hostname: adm2
  env_file: 
  - "adm/envfile"
  privileged: true
  networks:
   administracion:
    ipv4_address: 192.168.110.112
 dir1:
  build: ./dir
  hostname: dir1
  env_file: 
  - "dir/envfile"
  privileged: true
  networks:
   direccion:
    ipv4_address: 192.168.111.112
 sat1:
  build: ./sat
  hostname: sat1
  env_file: 
  - "sat/envfile"
  privileged: true
  networks:
   sat:
    ipv4_address: 192.168.112.113
 sat2:
  build: ./sat
  hostname: sat2
  env_file: 
  - "sat/envfile"
  privileged: true
  networks:
   sat:
    ipv4_address: 192.168.112.122
 rl:
  build: ./rl
  hostname: rl
  env_file: 
  - "rl/envfile"
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   administracion:
    ipv4_address: 192.168.110.201
   direccion:
    ipv4_address: 192.168.111.201
   sat:
    ipv4_address: 192.168.112.201
 rdi:
  build: ./rdi
  hostname: rdi
  env_file: 
  - "rdi/envfile"
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   sat:
    ipv4_address: 192.168.112.202
   dmz:
    ipv4_address: 192.168.120.202
 rde:
  build: ./rde
  hostname: rde
  env_file: 
  - "rde/envfile"
  privileged: true
  sysctls:
    net.ipv4.ip_forward: 1
  networks:
   dmz:
    ipv4_address: 192.168.120.203
 www:
  build: ./dmz
  hostname: www
  env_file: 
  - "dmz/envfile"
  privileged: true
  networks:
   dmz:
    ipv4_address: 192.168.120.121
networks:
  administracion:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.110.0/24
  direccion:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.111.0/24
  sat:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.112.0/24
  dmz:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.120.0/24
